# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Code
      labels:
        - python
        - enhancement
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
