site_name: tclf
site_description: tclf, a scikit-learn-compatible implementation of popular trade classification algorithms to classify financial markets transactions into buyer- and seller-initiated trades.
site_url: https://karelze.github.io/tclf/

theme:
  custom_dir: docs/overrides
  logo: img/logo.png
  favicon: img/favicon.ico
  name: material
  darkMode: true
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: black
      accent: indigo
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      accent: indigo
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: black
      accent: indigo
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.instant.progress
    - search.suggest
    - search.highlight

repo_name: karelze/tclf
repo_url: https://github.com/karelze/tclf
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Rules: rules.md
  - API reference: reference.md
  - Examples:
    - Option trade classification: option_trade_classification.md
  - More:
    - Naming conventions: naming_conventions.md
    - Handling of NaNs: nan_handling.md

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - pymdownx.arithmatex:
      generic: true


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
  - bibtex:
      bib_file: "docs/bibliography.bib"
      csl_file: "docs/apa-6th-edition.csl"
      cite_inline: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/karelze/tclf
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/markus-bilz/

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
