# https://packaging.python.org/en/latest/tutorials/packaging-projects/
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "otc"
authors = [
  { name="Markus Bilz", email="github@markusbilz.com" },
]
description = "Code to perform option trade classification using machine learning."
readme = "README.md"
license = {file = "LICENSE.txt"}
requires-python = ">=3.8"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Framework :: Jupyter",
  "Operating System :: OS Independent",
]

dynamic = ["version"]

[project.optional-dependencies]
dev = [
  "autoflake",
  "black",
  "coverage",
  "flake8",
  "isort",
  "mypy",
  "pre-commit",
  "pytest",
  "pytest-cov",
  "sphinx",
  "tox",
]

[project.urls]
"Homepage" = "https://github.com/KarelZe/thesis"
"Bug Tracker" = "https://github.com/KarelZe/thesis/issues"

[tool.autoflake]
recursive = true
in-place = true
ignore-init-module-imports = true
remove-all-unused-imports = true
remove-unused-variables = true

[tool.isort]
profile = "black"

[tool.mypy]
# https://github.com/python/mypy/issues/2410
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_untyped_calls = true
disallow_incomplete_defs = true

[tool.poetry]
name = "tclf"
version = "0.1.0"
description = "Library to perform trade classifcation."
authors = ["Markus Bilz <github@markusbilz.com>"]
readme = "README.rst"
packages = [{include = "tclf"}]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.25.1"
pandas = "^2.0.3"
scikit-learn = "^1.3.0"

[tool.poetry.group.dev.dependencies]
myst-parser = "^2.0.0"
furo = "^2023.7.26"
numpydoc = "^1.5.0"
sphinx-gallery = "^0.13.0"
matplotlib = "^3.7.2"

[tool.pylint.TYPECHECK]
# List of members which are set dynamically and missed by Pylint inference
# system, and so shouldn't trigger E1101 when accessed.
generated-members=["numpy.*", "torch.*"]

[tool.pytest.ini_options]
minversion = 7.0
addopts = "-ra -p no:warnings -v --cov --cov-report term-missing"
pythonpath = ["src"]
testpaths = ["tests"]

[tool.coverage.run]
omit = [
    "debug_*.py",
    "tclf/tests/*",
]
