# adapted from https://browniebroke.com/blog/gh-action-pre-commit-autoupdate/
on:
  schedule:
    - cron: '0 0 * * *'
  push:
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Git switch to new branch
        run: git switch --create=${{ github.run_id }}-${{ github.run_attempt }}
      - name: Install pre-commit
        run: python -m pip install pre-commit
      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate
      - name: Create pull request
        run: |
          if git diff --exit-code then
          else
            # https://github.com/cli/cli/issues/6485#issuecomment-1287937905
            gh pr create --base main --head karelze:${{ github.run_id }}-${{ github.run_attempt }} --assignee "karelze" --title "Auto-update pre-commit hooks" --body "Update versions of tools in pre-commit configs to latest version"
          fi
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
