name: Pre-commit auto-update
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Git branch
        run: git branch autoupdate-pre-commit
      - name: Install pre-commit
        run: python -m pip install pre-commit
      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate
      - name: Git add and commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto-update pre-commit hooks" -m "Update versions of tools in pre-commit configs to latest version"
      - name: Create pull request
        run: gh pr create --base main --fill --assignee "@me"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
