name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docs.yaml'
      - 'zensical.toml'
      - 'docs/**'
      - 'src/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Git clone
        uses: actions/checkout@v6

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Build docs
        run: uv run zensical build

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
