name: Tests
on:
  push:
    paths:
      - '**/*'
      - '!docs/**'
jobs:
  build:
    name: test with ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.13"
        os: [ubuntu-latest]
    steps:
    - name: Git clone
      uses: actions/checkout@v4
    - name: Install uv and python
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
            uvx --with tox-uv tox
    - name: run tests with tox
      run:  tox -e test
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        verbose: true
    - name: Run benchmarks
      if: matrix.os == 'ubuntu-latest'
      uses: CodSpeedHQ/action@v3
      with:
        token: ${{ secrets.CODSPEED_TOKEN }}
        run: pixi run test --codspeed
