name: Tests
on:
  push:
    paths:
      - '**/*'
      - '!docs/**'
jobs:
  build:
    name: test with ${{ matrix.env }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        env:
          - ["3.9", "3.13"]
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Git clone
      uses: actions/checkout@v4
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v3
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
          uv venv
          uv pip install tox
    - name: run tests with tox
      run: uvx tox -e test
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        verbose: true
    - name: Run benchmarks
      if: matrix.os == 'ubuntu-latest'
      uses: CodSpeedHQ/action@v3
      with:
        token: ${{ secrets.CODSPEED_TOKEN }}
        run: pixi run test --codspeed
